/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection { 'title' : string, 'content' : string }
export type ExternalBlob = Uint8Array;
export interface ResinArtPiece {
  'id' : string,
  'title' : string,
  'resinThickness' : [] | [bigint],
  'description' : string,
  'isVanGogh' : boolean,
  'isTriptych' : boolean,
  'image' : ExternalBlob,
  'isNew' : boolean,
  'frameMaterial' : [] | [string],
  'isFragmented' : boolean,
  'resinEffect' : boolean,
}
export interface StudioInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
  'distribution' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addResinArtPiece' : ActorMethod<
    [
      string,
      string,
      string,
      ExternalBlob,
      boolean,
      [] | [bigint],
      [] | [string],
      boolean,
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'getAboutSection' : ActorMethod<[], [] | [AboutSection]>,
  'getAllResinArtPieces' : ActorMethod<[], Array<ResinArtPiece>>,
  'getResinArtPiece' : ActorMethod<[string], [] | [ResinArtPiece]>,
  'getStudioInfo' : ActorMethod<[], [] | [StudioInfo]>,
  'setAboutSection' : ActorMethod<[string, string], undefined>,
  'setStudioInfo' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];