/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AboutSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ResinArtPiece = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'resinThickness' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'isVanGogh' : IDL.Bool,
  'isTriptych' : IDL.Bool,
  'image' : ExternalBlob,
  'isNew' : IDL.Bool,
  'frameMaterial' : IDL.Opt(IDL.Text),
  'isFragmented' : IDL.Bool,
  'resinEffect' : IDL.Bool,
});
export const StudioInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'distribution' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addResinArtPiece' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Bool,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
  'getAllResinArtPieces' : IDL.Func([], [IDL.Vec(ResinArtPiece)], ['query']),
  'getResinArtPiece' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ResinArtPiece)],
      ['query'],
    ),
  'getStudioInfo' : IDL.Func([], [IDL.Opt(StudioInfo)], ['query']),
  'setAboutSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStudioInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AboutSection = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const ResinArtPiece = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'resinThickness' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'isVanGogh' : IDL.Bool,
    'isTriptych' : IDL.Bool,
    'image' : ExternalBlob,
    'isNew' : IDL.Bool,
    'frameMaterial' : IDL.Opt(IDL.Text),
    'isFragmented' : IDL.Bool,
    'resinEffect' : IDL.Bool,
  });
  const StudioInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'distribution' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addResinArtPiece' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Bool,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'getAboutSection' : IDL.Func([], [IDL.Opt(AboutSection)], ['query']),
    'getAllResinArtPieces' : IDL.Func([], [IDL.Vec(ResinArtPiece)], ['query']),
    'getResinArtPiece' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ResinArtPiece)],
        ['query'],
      ),
    'getStudioInfo' : IDL.Func([], [IDL.Opt(StudioInfo)], ['query']),
    'setAboutSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStudioInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };